theme = "vanilla-bootstrap-hugo-theme"
baseURL = "https://statistics-mdr-2022-01.netlify.app"
languageCode = "en-us"
title = "Estadística I."


# Uncomment below to enable syntax hghlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "MDR"
    pre = "MDR"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Clase"
    pre = "edit"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = ""
    pre = "maths"
    url = ""
    weight = 3
  [[menu.nav]]
    name = ""
    pre = "smile"
    url = ""
    weight = 4
  [[menu.nav]]
    name = ""
    pre = "rss"
    url = ""
    weight = 5  
  [[menu.nav]]
    name = ""
    pre = "aka"
    url = ""
    weight = 6
[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Maestría en Desarrollo Regional. Semestre 2022-01."
  footerText = "José Luis Manzanares Rivera.2022"
  hideFooter = false
  math= true