---
title: "lineplot1"
author: "Jose´Luis Manzanares Rivera"
date: 2021-01-11T21:13:14-05:00
output: html_document
---

```{r,,echo = FALSE, eval = TRUE, message=FALSE,warning = FALSE}
suppressPackageStartupMessages(library(tidyverse))
```

##Análisis de Tendencias usando intervalos de confianza 

#### Dominio de aplicacion: Medio Ambiente  Ensenada, BC. Periodo:   1969-2011

#### Objetivo aprender a analizar datos en formato temporal. Verbos aprendidos en el contexto tidy: gather, mutate, group_by, summarise, arrange.

##### Plataforma de visualización: ggplot2. 

```{r,  fig.height = 8, fig.width = 12, include=FALSE, cache = TRUE, echo = FALSE, warning = FALSE  }

BC2001<-read.csv("ema_2001_AGUACALIENTE.csv")%>%
  rename(max=tmin,min=tmax)


df<-BC2001%>%
mutate(max=as.numeric(as.character(max)),min=as.numeric(as.character(min)) )

temp<-mutate(df,date=as.Date(FECHA, "%d/%m/%Y"))%>%
mutate(mes=as.integer(substr(FECHA,4,5)),año=substr(FECHA,7,10))

meses<-data.frame(Meses=c("Enero ",	"Febrero",	"Marzo",	"Abril",	"Mayo",	"Junio",	"Julio",	"Agosto",	"Septiembre",	"Octubre",	"Noviembre",	"Diciembre"),mes=seq(1, 12, by=1))


temp1<-left_join(meses,temp)


prom_yr<-temp%>%na.omit()%>%
  group_by(mes,año)%>%
  summarise(max_med=mean(max), min_med=mean(min))


promedio_arr<-arrange(prom_yr,año,mes)
glimpse(promedio_arr)


eneros<-filter(promedio_arr, mes==1)%>%
  mutate(año=as.numeric(año))%>%ungroup()%>%
  select(-mes)

## Organizamos   nuestra estructura de datos en formato tidy: variable por columna. Así necesitamos dos nuevas variables que serán los dos promeros argumetnos en la función gather: Una nueva variable categórica que llamaremos type, esta denota las dos categorias que tenemos en nuestos datos de temperatura max_med  y min_med. Y una segunda que llamaremos temp para denotar el valor nominal, (la medición numerica, el dato) de la temperatura.

# El tercer argumento solo es el rango de variables que vamos a reorganizar en las dos nuevas variables type  y temp. 


eneros_tidy<-eneros%>%
  gather(type,temp,max_med:min_med)
data("EuStockMarkets")
xx = EuStockMarkets[,1]
ti = 1:length(xx)
ggplot(eneros_tidy, aes(año, temp, col=type)) + 
geom_line()  +
geom_smooth()+
  theme_light()+
xlab("Año")+ylab("Temperatura (c°)")+
   scale_color_discrete(labels=c("Tmax", "Tmin"))+
  labs(colour="Temperatura")+ theme(legend.position="top")+
scale_colour_brewer(palette="Set1")

ggsave("C:/Users/LENOVO/Desktop/DESK/I/2019/CONVID/graphs/tmaxmin.tiff",width = 20, height = 14, units = "cm",dpi=300)
```