---
title: ""
author: "JLMR"
date: "13/1/2021"
output: html_document
---



```{r set-global-options, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = FALSE, 
                      cache = FALSE,
                      include = TRUE,
                      collapse = FALSE,
                      dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = FALSE)                     

```






```{r silent-packages, echo = FALSE, eval = TRUE, message=FALSE, include = FALSE}

library(ggplot2)
library(tidyverse)
```


## Visualización 
### Dispersión


Práctica [Series de tiempo y lineas de regresión](https://raw.githubusercontent.com/JoseLuisManzanaresRivera/intersemestral-2021/main/content/post/lineplot_temp_ensenada.Rmd)

Práctica [Rango intercuartil, percentiles y outliers: Boxplot](https://raw.githubusercontent.com/JoseLuisManzanaresRivera/intersemestral-2021/main/content/post/dtools-Scatterplot.Rmd)

Sesión 3 práctica [Scatter](https://raw.githubusercontent.com/JoseLuisManzanaresRivera/intersemestral-2021/main/content/post/scatterplot.Rmd)

Práctica [Funciones de densidad para analizar distribución y prueba de hipótesis](https://raw.githubusercontent.com/JoseLuisManzanaresRivera/intersemestral-2021/main/content/post/Density.Rmd)


Sesión 3 práctica [scatter prueba de hipótesis](https://raw.githubusercontent.com/JoseLuisManzanaresRivera/intersemestral-2021/main/content/post/Density.Rmd)