---
title: "Unidad 2"
author: "José Luis Manzanares Rivera"
date: 2022-10-04T22:08:14-05:00
categories: ["Distribución normañ"]
tags: ["Probabilidad"]
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="probabilidad." class="section level1">
<h1>Probabilidad.</h1>
<div id="objetivos" class="section level3">
<h3>Objetivos:</h3>
<ul>
<li><p>Concer el concepto y las reglas de probabilidad</p></li>
<li><p>Estudiar la definición de variables aleatorias.</p></li>
<li><p>Reconocer la importancia de la distribución normal y sus propiedades</p></li>
<li><p>Presentar las distribuciones de probabilidad.</p></li>
</ul>
<div id="meta-de-aprendizaje" class="section level4">
<h4>Meta de aprendizaje:</h4>
<p>Entender probabilidad básica y distribuciones probabilisticas.</p>
<p><a href="https://drive.google.com/file/d/1ezHlHeEPXBDIf2glXMsyZ0KzGsR8pM27/view?usp=sharing">Libro de texto para consulta para el tema de la sesión de hoy.</a></p>
</div>
</div>
<div id="definiciones." class="section level2">
<h2>Definiciones.</h2>
<p><strong>Experimentos aleatorios:</strong> Los resultados de eventos cuyo resultado es incierto por ejemplo:</p>
<ul>
<li><p>Lanzar una moneda puede tener el resultado de Sol <strong>S</strong> simbolizado como 0 y águila <strong>A</strong>, simbolizado como 1. Lo que integra el conjunto {S,A}, {0,1}.</p></li>
<li><p>Lanzamiento de un dado con el resultado uno de los números en el conjunto {1,2,3,4,5,6}.</p></li>
</ul>
<p><strong>Población</strong> Incluye todos los elementos de un conjunto de datos.</p>
<p><strong>Muestra</strong> Consiste en una o más observaciones de la población.</p>
<p><strong>Espacio muestral:</strong> Un conjunto <strong>M</strong> que consta de todos los resultados posibles de un experimento aleatorio se denomina espacio muestral.</p>
<div id="eventos." class="section level5">
<h5>Eventos.</h5>
<p>Un evento es un subconjunto <strong>A</strong> del espacio muestral <strong>M</strong>. Esto es un conjunto de resultados posibles.</p>
<p><strong>Por ejemplo</strong>, si lanzamos una moneda <strong>dos veces</strong>, el evento de que solo resulte una águila, es el subconjunto del espacio muestral que consta de los puntos (0,1)(1,0). La figura siguiente muestra este subconjunto en el espacio muestral.</p>
<p><img src="/img/espacioM.jpg" /></p>
</div>
<div id="operaciones-de-conjuntos-en-un-espacio-muestral" class="section level5">
<h5>Operaciones de conjuntos en un espacio muestral</h5>
<p><img src="/img/reglasprob1.jpg" />
<img src="/img/concepto1.jpg" /></p>
<p>El enfoque axiomático es preferible desde un punto de vista matemático de la probabilidad.</p>
<p><img src="/img/axiiomas.jpg" /></p>
</div>
<div id="teoremas-importantes-sobre-probabilidad." class="section level4">
<h4>Teoremas importantes sobre probabilidad.</h4>
<p><img src="/img/teoremas1.jpg" /></p>
</div>
<div id="asignación-de-probabilidades." class="section level3">
<h3>Asignación de probabilidades.</h3>
<p><img src="/img/prob1x.jpg" /></p>
<div id="ejercicio." class="section level4">
<h4>Ejercicio.</h4>
<p>Aplicando las definiciones anteriores en el experimento de lanzar una moneda, nosotros podemos calcular las probabilidades para los eventos <strong>E</strong> posibles de un total de resultados <strong>n</strong></p>
<p>En este caso la probabilidad de que caiga águila será <span class="math display">\[P[A]=\frac{1}{2}=.50\]</span></p>
<p>Determine la probabilidad de que al lanzar dos monedas caiga al menos un sol.</p>
<p>Primero determinamos los elementos que componen el evento muestral.</p>
<p>“Al menos un sol”.</p>
<p>A={sa, as, ss}. Ahora nos preguntamos, ¿cuántos resultados posibles hay?.</p>
<p>Si son dos lanzamientos hay 4 resultados posibles. Y ¿cuántos elementos componen el evento muestal? Son tres posibles elementos los que integran el evento muestral que cumple la proposición. <strong>“Al menos un sol”.</strong></p>
<p>La probabilidad será <span class="math display">\[P[A]=\frac{3}{4}\]</span> en palabras, hay una probabilidad del <span class="math inline">\(75\%\)</span> de obtener al menos una sol en estos dos lanzamientos.</p>
<p>De manera complementaria hay una probabilidad del <span class="math inline">\(25\%\)</span> de <strong>no</strong> obtener <strong>“al menos un sol”</strong> en los dos lanzamientos.</p>
<p>En general si <strong>A</strong> es el evento muestral y <strong>h</strong> un evento sencillo (resultado posible entre A), entre <strong>n</strong> posibles elementos, entonces la probabilidad de A , esta definida por <span class="math display">\[P[A]=\frac{h}{n}\]</span></p>
</div>
<div id="ejemplo" class="section level4">
<h4>Ejemplo:</h4>
<p>Sea M ={1,2,3,4,5,6} el epacio muestral, para un experimento de un lanzamiento de un dado balanceado de 6 caras, entonces la probabiliad de <span class="math inline">\(P(A)=P(1)=...=P(6)=\frac{1}{6}\)</span></p>
<div id="ejercicios" class="section level5">
<h5>Ejercicios</h5>
<p>1.-Determine la probabilidad de enontrar un 2 U 5. P(2U5)=P(2)+P(5)=?</p>
<p>2.- Determine la probabilidad de encontrar un número par. P{2,4,6}=?</p>
</div>
</div>
<div id="ejercicio-empleando-software." class="section level4">
<h4>Ejercicio empleando software.</h4>
<p>Genere un <strong>dado virtual:</strong></p>
<pre class="r"><code>1:6</code></pre>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>Este notación nos permite tener un lista de números entre 1 y 6, pero es necesario almacenarlos. Para lo cual asignamos un nombre usando el símbolo <strong>$&lt;-</strong> que equivale a decir igual que.</p>
<pre class="r"><code>Dado&lt;-1:6
Dado</code></pre>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p><strong>Note:</strong> Cuando creamos un objeto este aparece en la parte superior derecha en el área de environment.</p>
<p><img src="/environment.jpg" /></p>
<pre class="r"><code>## Pruebe generar dados de diferente número de caras.

dado&lt;-1:10
dado</code></pre>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<pre class="r"><code>dado&lt;-1:6
dado</code></pre>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<pre class="r"><code>dadosietecaras&lt;-1:7
dadosietecaras</code></pre>
<pre><code>## [1] 1 2 3 4 5 6 7</code></pre>
<p>Para nuestro propósito de obtener un número aleatorio en un lanzamiento de dado, podemos utilizar la funciòn <strong>sample</strong>, esta toma <strong>dos argumentos</strong>, el vector <strong>x</strong> y el tamaño de la muestra.</p>
<pre class="r"><code>sample(x=dado,size=1)</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code>sample(x=1:6,size=1)</code></pre>
<pre><code>## [1] 2</code></pre>
<p>Es posible omitir la etiqueta del argumetno si recordamos que argumento corresponde con la posición, pero en funciones de mayor tamaño es de ayuda anotar el nombre ya que no siempre recordamos los nombres de todos los argumentos.</p>
<pre class="r"><code>sample(dado,1)</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>sample(1:6,1)</code></pre>
<pre><code>## [1] 2</code></pre>
</div>
</div>
</div>
<div id="muestreo-con-reemplazo." class="section level2">
<h2>Muestreo con reemplazo.</h2>
<p>Cuando aplicamos la función <code>sample(dado, size = 2)</code> notemos que nunca obtenemos dos veces el mismo valor, esto es la función de forma predeterminada considera una muestra aleatoria pero sin reemplazo, para evitar este comportamiento y poder simular el lanzamiento de un dado en realidad en donde podemos obtener por ejemplo el valor 3 y luego otro 3, es necesario inlcuir el argumeto <code>replace = TRUE</code>, esto permite que una vez que lanzamos el primer dado, sea posible obtener el mismo valor en el segundo lanzamiento, tal como sucede en el caso real.</p>
<pre class="r"><code>sample(dado, size = 2, replace = TRUE)</code></pre>
<pre><code>## [1] 4 4</code></pre>
<p>El muestreo con reemplazo es una manera fácil de crear muestras aleatorias simples.</p>
<p>Por ejemplo simular correctamente el lanzamiento de un dado en el que obtenemos <strong>un número aleatorio</strong> <strong>independiente</strong> cada vez.</p>
<p>Si deseas sumar el valor del dado para los dos lanzamientos, unicamente aplicamos la función de suma y tenemos el resultado de esta simulación con números aleatorios.</p>
<pre class="r"><code>dados &lt;- sample(dado, size = 2, replace = TRUE)
dados</code></pre>
<pre><code>## [1] 5 2</code></pre>
<hr />
<div id="distribuciones-de-probabilidad." class="section level3">
<h3>Distribuciones de probabilidad.</h3>
<p>¿A qué nos referimos cuando hablamos de distribuciones de probabilidad?</p>
<p>A las <strong>herramientas matemáticas</strong> para describir la distribución de datos numéricos en poblaciones y muestras.</p>
<div id="definiciones" class="section level5">
<h5>Definiciones:</h5>
<ul>
<li><p><strong>Parámetro</strong> Característica de una población, tal como la media o la desviación estándar. Frecuentemente se utilizan <strong>letras griegas</strong> para referirnos a una parámetro.</p></li>
<li><p><strong>Estadístico</strong> Una característica medible de una <strong>muestra</strong>.</p></li>
</ul>
<p><strong>Ejemplos de una estadistico:</strong></p>
<ul>
<li>La media de la muestra</li>
<li>El rango de la muestra</li>
<li>La desviación de los datos respecto a la media.</li>
</ul>
<p><img src="/img/samples.jpg" /></p>
<p>Si no conocemos el <strong>paramétro</strong> (ingreso medio de los trabajadores en Baja california), podemos estimar el <strong>estadístico</strong> de una <strong>muestra</strong> y a partir de este <strong>inferir</strong> el parámetro <strong>poblacional</strong></p>
<p>La representatividad de la <strong>muestra</strong> es importante para la validéz del <strong>estadístico</strong> que permite inferir el <strong>parámetro</strong> de interés.</p>
<p>El correcto diseño de nuestros análisis permite que las <strong>muestras</strong> seleccionadas constituyan una adecuada representación de la <strong>población de estudio</strong>.</p>
<ul>
<li><p><strong>Distribución de muestreo</strong> La distribución de probabiliad de un estadístico dado. Con base en una muestra aleatoria.</p></li>
<li><p><strong>Inferencia estadística</strong> Te permite hacer una conjetura “educada” respecto de un parámetro poblacional, basado en un estadístico calculado usando una muestra aleatoria de la población.</p></li>
</ul>
<p><strong>Convención sobre la notación:</strong>
Los Parámetros (poblacionales) son denotados generalmente con el uso de letras griegas. Mientras los estadísticos (muestrales) son expresados con letras convencionales.</p>
<p><strong>Ejemplo.</strong></p>
<p>Parámetro poblacional <span class="math inline">\(\mu\)</span>, Desv std <span class="math inline">\(\sigma\)</span>
Estadístico muestral <span class="math inline">\(\bar{x}\)</span> Desv std <strong>S</strong></p>
</div>
</div>
</div>
<div id="distribución-normal." class="section level2">
<h2>Distribución normal.</h2>
<p>Una <strong>caso particular de la distribución esta dado cuando observamos simetría</strong> (ej. media, mediana son iguales).</p>
<p>En este caso, ambos lados de la función de densidad integran <strong>la misma proporción de datos</strong>.</p>
<p>En términos de su forma, estas curvas además de ser <strong>simétricas</strong> tiene un sólo pico, (no tiene dos <strong>modas</strong> no son bimodales) y tienen forma de <strong>campana</strong>.</p>
<p>La curva de densidad de una distribución de datos <strong>normal</strong>, se describe completamente a partir de su media <span class="math inline">\(\mu\)</span> y desviación estándar <span class="math inline">\(\sigma\)</span></p>
<p>Y la podemos denotar <span class="math inline">\(N(\mu, \sigma)\)</span></p>
<p>Considere los dos ejemplos siguientes, <strong>ambos son escenarios de distribuciones normales</strong>, aunque el grado de dispersión es mayor en el primer caso.</p>
<p>El parámetro <span class="math inline">\(\sigma\)</span> controla el grado de dsipersión de la <strong>curva normal</strong>.</p>
<p><img src="/img/normalidad.jpg" /></p>
<p>En términos gráficos, el <strong>punto de inflexión</strong>, se ubica a una distancia de magnitud <span class="math inline">\(\sigma\)</span> respecto de <span class="math inline">\(\mu\)</span>.</p>
<p><img src="/img/inflexion.jpg" /></p>
</div>
<div id="paricularidades-de-la-distribución-normal." class="section level2">
<h2>Paricularidades de la distribución normal.</h2>
<p>Una particularidad relevante de las distribuciones normales es que cumplen con la siguiente regla:</p>
<ul>
<li><p>El <strong>68%</strong> de los datos se localiza a una <span class="math inline">\(+,- \sigma\)</span> desviación estándar, de la media <span class="math inline">\(\mu\)</span>.</p></li>
<li><p>El <strong>95%</strong> de los datos se localiza a <span class="math inline">\(+,- 2\sigma\)</span> de la media <span class="math inline">\(\mu\)</span></p></li>
<li><p>El <strong>99.7%</strong> de los datos se localiza a <span class="math inline">\(+,- 3\sigma\)</span> de la media <span class="math inline">\(\mu\)</span></p></li>
</ul>
<p><img src="/img/regla_normal.jpg" /></p>
<div id="por-qué-tanto-énfasis-en-las-distribciones-normales" class="section level3">
<h3>¿Por qué tanto énfasis en las distribciones normales?</h3>
<ul>
<li><p>Porque describen una gran cantidad de situaciones empíricas de naturaleza aleatoria.</p></li>
<li><p>Los procesos de <strong>inferencia estadística</strong> permiten resultados confiables (robusos) cuando se aplican a distribuciones simétricas.
Dependen de esta condición.</p></li>
</ul>
<div id="actividad-para-afianzar-los-conceptos" class="section level5">
<h5>Actividad para afianzar los conceptos</h5>
<p>Conteste las siguientes preguntas</p>
<p><img src="/img/preguntas.jpg" /></p>
<p>Para finalizar esta sección es importante notar que es frecuente usar los <strong>valores estandarizados</strong> de la distribución normal con fines de comparación de las distribuciones.</p>
<p>Estandarizar en este caso consiste en tomar un valor particular del conjunto de datos, restarle el valor de la media y dividirlo entre la desviación estándar.</p>
<p>A este valor estandarizado se le denomina <strong>Z Score</strong> y se obtiene <span class="math display">\[z=\frac{x-\mu}{\sigma}\]</span></p>
<p>Este <strong>score z</strong> nos indica a <strong>cuántas desviaciones estándar</strong> se encuentra la observación original de la <strong>media</strong> y en qué dirección.</p>
<p>Por <strong>ejemplo</strong>, considerando los datos del ejercicio anterior, vemos que la media <span class="math inline">\(\mu=110\)</span>, <span class="math inline">\(\sigma=25\)</span>, por lo que el coeficiente estandarizado de una persona cuyo IQ= 150, será <span class="math display">\[z=\frac{150-110}{25}=1.6\]</span>.</p>
<p>Y se interpreta como la distancia en términos de desviaciones estándar respecto a la media. Así el dato IQ de 150 se ubica a una distancia de 1.6 desviaciones estandar de la media.</p>
<p>Las observaciones <strong>mayores</strong> que la media
son positivas y las <strong>menores</strong>, negativas.</p>
<p>Resumiendo: El <strong>proceso de estandarización</strong> unicamente permite exprezar los valores de las distribución en relación a una <strong>escala común</strong>, en este caso, una <strong>distancia respecto a la media</strong>.</p>
<p>En términos generales la <strong>distribución normal estandarizada</strong>, se expreza con los parámetros media cero y desviación estándar = 1 o bien <span class="math display">\[N(0,1)\]</span> <span class="math display">\[z=\frac{x-\mu}{\sigma}\]</span></p>
<p><strong>Tarea. Se recomineda revisar el material del libro de texto:</strong></p>
<p><a href="https://drive.google.com/file/d/1sbwcTP-k7_EKmY406BVYUwLiMZENKzCs/view?usp=sharing">Libro de texto</a> sección 1.44, páginas 64-79.</p>
<p><strong>Ejercicio</strong></p>
<p><img src="/img/Z-scores.jpg" /></p>
<p>Una vez que sabemos cómo estandarizar un valor determinado. Es posible usar este <strong>Z-score</strong> para determinar</p>
</div>
<div id="qué-proporción-de-los-datos-estan-por-debajo-de-este-valor-estandarizado-z-score" class="section level5">
<h5>¿Qué proporción de los datos estan por debajo de este valor estandarizado z-score?</h5>
<p><img src="/img/tablanormal.jpg" /></p>
<p>Las tablas de la distribción Z, dan esta información pero, actualmente es poco frecuente usar estas tablas en lugar de esto podemos estimarlo usando un software.</p>
<p>Ejemplo:</p>
<p>¿Qué proporción de los paises en el continente americano tienen un ingreso percapita superior a 10 000 USD?</p>
<p>Pasos para responder la pregunta.</p>
<p>1.- Estimar Media y desviación estandar</p>
<pre class="r"><code>zscore&lt;-gapminder%&gt;%filter(continent==&quot;Americas&quot;)

summary(zscore)</code></pre>
<pre><code>##       country       continent        year         lifeExp     
##  Argentina: 12   Africa  :  0   Min.   :1952   Min.   :37.58  
##  Bolivia  : 12   Americas:300   1st Qu.:1966   1st Qu.:58.41  
##  Brazil   : 12   Asia    :  0   Median :1980   Median :67.05  
##  Canada   : 12   Europe  :  0   Mean   :1980   Mean   :64.66  
##  Chile    : 12   Oceania :  0   3rd Qu.:1993   3rd Qu.:71.70  
##  Colombia : 12                  Max.   :2007   Max.   :80.65  
##  (Other)  :228                                                
##       pop              gdpPercap    
##  Min.   :   662850   Min.   : 1202  
##  1st Qu.:  2962359   1st Qu.: 3428  
##  Median :  6227510   Median : 5466  
##  Mean   : 24504795   Mean   : 7136  
##  3rd Qu.: 18340309   3rd Qu.: 7830  
##  Max.   :301139947   Max.   :42952  
## </code></pre>
<pre class="r"><code>sd(zscore$gdpPercap)</code></pre>
<pre><code>## [1] 6396.764</code></pre>
<p>La media <span class="math inline">\(\mu=7136\)</span> y la desviación estándar es <span class="math inline">\(\sigma=6396.764\)</span>
Entonces la caracterización de la distribución esta dada por (7136, 6396.764)</p>
<p><strong>Paso 2</strong></p>
<p>Estandarizamos el valor solicitado en el problema a z-score. Sabemos que <span class="math display">\[z=\frac{x-\mu}{\sigma}\]</span>, entonces</p>
<pre class="r"><code>z=(10000-7136)/6396.764
z</code></pre>
<pre><code>## [1] 0.4477264</code></pre>
<p>El <strong>z-score</strong> para un ingreos de 10 000 es de <strong>0.4477264</strong>, lo que indica que la distancia, <strong>en desviaciones estándar</strong> desde la <strong>media</strong>, para un ingreso de 10 000 es de 0.4477264.</p>
<p><strong>Paso 3</strong> Estimar la proporción por debajo de la curva para el valor estandarizado.</p>
<p>Con esta información determinamos la proporción de paises cuyo ingreso es inferior buscando los datos en la <a href="https://drive.google.com/file/d/1sbwcTP-k7_EKmY406BVYUwLiMZENKzCs/view?usp=sharing">tabla A pagina 786 del libro</a>.</p>
<p><strong>Alternativamente podemos usar R para determinar este valor.</strong></p>
<p>El argumento requerido por la función en R es el <strong>z-score</strong> previamente calculado y el resultado es la proporción de observaciones por debajo de la curva a la izquierda de este valor.</p>
<pre class="r"><code>pnorm(0.4477264)</code></pre>
<pre><code>## [1] 0.6728247</code></pre>
<p>Note el orden de los argumentos, en la opción previa usamos unicamente el valor estandarizado. <strong>z-score.</strong></p>
<pre class="r"><code>pnorm(10000,7136,6396.764)</code></pre>
<pre><code>## [1] 0.6728247</code></pre>
<p>En este caso los argumentos son: valor de interés, <span class="math inline">\(\mu=7136\)</span> y <span class="math inline">\(\sigma=6396.764\)</span></p>
<p><strong>En conclusión</strong>, dado que el 0.6728247 <span class="math inline">\((67.28\%)\)</span> de los países tienen un ingreso inferior a 10 000 USD, podemos concluir que 1- 0.6728247, tendrá un ingreso superior.</p>
<p>La respuesta a la pregunta es <span class="math inline">\(0.3271753\)</span> o <span class="math inline">\(32.71\%\)</span></p>
<p><strong>Tip</strong> Si conocemos la caracterización de la función podemos usar directamente la función <code>pnorm</code> para estimar también el <strong>z-score</strong>. ej. pnorm(valor, <span class="math inline">\(\mu\)</span> , <span class="math inline">\(\sigma\)</span>)</p>
</div>
</div>
</div>
</div>
